In [4]:
import numpy as np

In [5]:
filas = 3
columnas= 3
# #######
ma = []
elem = 0
for i in range(filas):
    fila = []
    for j in range(columnas):
        fila.append(elem)
        elem += 1
    ma.append(fila)

print(ma)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [9]:
m=np.identity(6)
print(m)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
